# System Integration Intake Configuration
name: "intake-integration"
description: "Initial requirements gathering for ServiceNow system integration requests. Quick user-facing session (3-5 minutes) to capture problem statement, business impact, and initial requirements."
author: "Alex the Facilitator"

# Critical variables load from config_source
config_source: "{bundle-root}/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
project_name: "{config_source}:project_name"
date: system-generated

# Session variables (auto-populated by workflow engine - Story 5.0)
session_id: ""
session_folder: "{project-root}/data/agent-outputs/{{session_id}}"
manifest_file: "{session_folder}/manifest.json"

# Module path and component files
installed_path: "{bundle-root}/workflows/intake-integration"
template: "{bundle-root}/templates/initial-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "System Integration"
request_type: "integration"

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{session_folder}/output.md"