# ServiceNow Epic Review Workflow Configuration
name: "review-epic"
description: "Comprehensive epic-level review of all stories. Pixel performs deep analysis of story quality, logical ordering, dependency validation, and requirements coverage to ensure the epic is development-ready."
author: "Pixel the Story Developer"

date: system-generated

# Module path and component files
installed_path: "pixel/workflows/review-epic"
template: "pixel/templates/story-template.md"
instructions: "{installed_path}/instructions.md"

# Input configuration
epic_folder_path: ""
requirements_doc_path: ""
epic_name: ""
project_slug: ""

# Output configuration - New structure
review_report_file: "{{project_slug}}/3-stories/review-epic-{{project_slug}}-{{date}}.md"
issues_log_file: "{{project_slug}}/3-stories/issues-{{project_slug}}-{{date}}.md"
