# ITSM Enhancement Deep-Dive Configuration
name: "deep-dive-itsm"
description: "Detailed requirements gathering for ServiceNow ITSM enhancements. BA/Developer-assisted session (30-45 minutes) that produces complete, development-ready requirements."
author: "Casey the Analyst"

# Critical variables load from config_source
config_source: "{bundle-root}/config.yaml"
output_folder: "{config_source}:output_folder"
sn_projects_folder: "{config_source}:sn_projects_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
project_name: "{config_source}:project_name"
date: system-generated

# Session variables (auto-populated by workflow engine - Story 5.0)
session_id: ""
session_folder: "{project-root}/data/agent-outputs/{{session_id}}"
manifest_file: "{session_folder}/manifest.json"

# Module path and component files
installed_path: "{bundle-root}/workflows/deep-dive-itsm"
template: "{bundle-root}/templates/detailed-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "ITSM Enhancement"
request_type: "itsm"

# Input from Mode 1 (optional - can start fresh if needed)
initial_requirements_path: ""

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{session_folder}/output.md"
