# Application Development Deep-Dive Configuration
name: "deep-dive-app"
description: "Detailed requirements gathering for ServiceNow application development. BA/Developer-assisted session (30-45 minutes) that produces complete, development-ready requirements."
author: "Casey the Analyst"

date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/sn/workflows/deep-dive-app"
template: "{project-root}/bmad/sn/templates/detailed-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Application Development"
request_type: "application"

# Input from Mode 1 (optional - can start fresh if needed)
initial_requirements_path: ""

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/2-requirements/detailed-{{project_slug}}-{{date}}.md"
