# Workflow Automation Intake Configuration
name: "intake-workflow"
description: "Initial requirements gathering for ServiceNow workflow automation requests. Quick user-facing session (3-5 minutes) to capture problem statement, business impact, and initial requirements."
author: "Alex the Facilitator"

date: system-generated

# Module path and component files
installed_path: "alex/workflows/intake-workflow"
template: "alex/templates/initial-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Workflow Automation"
request_type: "workflow"

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/1-intake/initial-{{project_slug}}-{{date}}.md"