# Reporting/Analytics Intake Configuration
name: "intake-reporting"
description: "Initial requirements gathering for ServiceNow reporting and analytics requests. Quick user-facing session (3-5 minutes) to capture problem statement, business impact, and initial requirements."
author: "Alex the Facilitator"

date: system-generated

# Module path and component files
installed_path: "alex/workflows/intake-reporting"
template: "alex/templates/initial-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Reporting/Analytics"
request_type: "reporting"

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/1-intake/initial-{{project_slug}}-{{date}}.md"