# Application Development Intake Configuration
name: "intake-app"
description: "Initial requirements gathering for ServiceNow application development requests. Quick user-facing session (3-5 minutes) to capture problem statement, business impact, and initial requirements."
author: "Alex the Facilitator"

# Critical variables load from config_source
config_source: "{bundle-root}/config.yaml"
output_folder: "{config_source}:output_folder"
sn_projects_folder: "{config_source}:sn_projects_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
project_name: "{config_source}:project_name"
date: system-generated

# Module path and component files
installed_path: "{bundle-root}/workflows/intake-app"
template: "{bundle-root}/templates/initial-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Application Development"
request_type: "application"

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{sn_projects_folder}/{{project_slug}}-{{date}}/1-intake/initial-{{project_slug}}-{{date}}.md"