# ServiceNow Story Building Workflow Configuration
name: "build-stories"
description: "Transform detailed requirements into clear, actionable user stories for ServiceNow development. Guided by Pixel, this workflow breaks down requirements into right-sized stories with comprehensive acceptance criteria."
author: "Pixel the Story Developer"

date: system-generated

# Module path and component files
installed_path: "pixel/workflows/build-stories"
template: "pixel/templates/story-template.md"
instructions: "{installed_path}/instructions.md"

# Input requirements document (user provides path)
requirements_doc_path: ""

# Project identification (gathered during workflow)
project_slug: ""

# Story configuration
epic_name: ""
story_number: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/3-stories/story-{{story_number}}.md"
epic_summary_file: "{{project_slug}}/3-stories/epic-{{project_slug}}-{{date}}.md"
