# ServiceNow Story Editing Workflow Configuration
name: "edit-stories"
description: "Make intelligent edits and adjustments to existing user stories. Pixel guides you through changes while detecting conflicts and ensuring story consistency."
author: "Pixel the Story Developer"

date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/sn/workflows/edit-stories"
template: "{project-root}/bmad/sn/templates/story-template.md"
instructions: "{installed_path}/instructions.md"

# Input story file (user provides path)
story_file_path: ""
epic_name: ""
story_number: ""

# Output configuration (overwrites existing or creates new version)
default_output_file: "{story_file_path}"
backup_file: "{story_file_path}.backup-{{date}}"
