# Portal/UI Customization Deep-Dive Configuration
name: "deep-dive-portal"
description: "Detailed requirements gathering for ServiceNow portal and UI customization. BA/Developer-assisted session (30-45 minutes) that produces complete, development-ready requirements."
author: "Casey the Analyst"

date: system-generated

# Module path and component files
installed_path: "casey/workflows/deep-dive-portal"
template: "casey/templates/detailed-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Portal/UI Customization"
request_type: "portal"

# Input from Mode 1 (optional - can start fresh if needed)
initial_requirements_path: ""

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/2-requirements/detailed-{{project_slug}}-{{date}}.md"
