# Application Development Intake Configuration
name: "intake-app"
description: "Initial requirements gathering for ServiceNow application development requests. Quick user-facing session (3-5 minutes) to capture problem statement, business impact, and initial requirements."
author: "Alex the Facilitator"

date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/sn/workflows/intake-app"
template: "{project-root}/bmad/sn/templates/initial-requirements.md"
instructions: "{installed_path}/instructions.md"

# Category specific
category: "Application Development"
request_type: "application"

# Project identification (gathered during workflow)
project_slug: ""

# Output configuration - New structure
default_output_file: "{{project_slug}}/1-intake/initial-{{project_slug}}-{{date}}.md"